HOST_NAME='localhost'
USER_NAME='hdi' 
USER_PASSWORD='hdi'
DATA_BASE_NAME='Final_Project'
TABLE_NAME='calls'
INPUT_CSV_PATH= r'/Users/angelaivonnesalgadobeltran/Documents/IronHack/Final project/cleaning_data/calls_clean_data.csv'
GENDER_BASE_VIOLENCE_DATA_BASE_NAME='gender_base_violence'
LOCALIZATION_TABLE_NAME='localization'