HOST_NAME='localhost'
USER_NAME='hdi' 
USER_PASSWORD='hdi'
DATA_BASE_NAME='Project_5'
TABLE_NAME='crimes'
INPUT_CSV_PATH= r'/Users/angelaivonnesalgadobeltran/Documents/IronHack/Projects/Project_5_Streamlit/Data/crimedata.csv'